apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/


patches:
- patch: |-
    - op: replace
      path: /spec/addresses/0
      value: 10.100.10.11-10.100.10.19
  target:
    kind: IPAddressPool
    name: first-pool