apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- issuer.yaml

namespace: cert-manager

helmCharts:
- name: cert-manager
  repo: oci://quay.io/jetstack/charts/cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  version: v1.18.2
  valuesInline:
    crds.enabled: "true"

